### ISSUE TITLE
I don't understand how to use capture function with custom button. Could you help me with some example

### ISSUE THREAD

**Issue by qwertyba1** [brettfazio/CameraView#1]
Hello, I tried to capture photo with custom button using your view. I saw capturePhoto function in your source code, but in dependencies it didn't appear. And using your source code I couldn't use this function because of private class restrictions. Could you help me with use of this function?

**Comment by brettfazio** [comment]
Hi @qwertyba1 , presently the capture photo button isn't 100% working. The core functionality in the view is working, but capture is not yet due to the way the data is exposed. If the private class restriction is the problem for you, you could fork the repo and clone it locally and use it there, making the private->public change.

**Comment by qwertyba1** [comment]
Thank you for quick response!
